# Generated by Django 5.0.6 on 2025-04-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagehub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagehub',
            options={'verbose_name': 'Pagehub', 'verbose_name_plural': 'Pageshub'},
        ),
        migrations.AlterField(
            model_name='pagehub',
            name='categoria_principal',
            field=models.CharField(choices=[('Ropa', 'Ropa'), ('Hogar/Deco', 'Hogar Deco'), ('Accesorios', 'Accesorios'), ('Recetas', 'Recetas'), ('Tecnología', 'Tecnologia'), ('Libros', 'Libros'), ('Plantas', 'Plantas'), ('Fotografía', 'Fotografia'), ('Académico', 'Academico')], max_length=20),
        ),
    ]
