# Generated by Django 5.1.7 on 2025-04-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagehub', '0002_alter_pagehub_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='categoria_principal',
            field=models.CharField(blank=True, choices=[('Ropa', 'Ropa'), ('Hogar-Deco', 'Hogar Deco'), ('Accesorios', 'Accesorios'), ('Recetas', 'Recetas'), ('Tecnologia', 'Tecnologia'), ('Libros', 'Libros'), ('Plantas', 'Plantas'), ('Fotografia', 'Fotografia'), ('Academico', 'Academico')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pagehub',
            name='categoria_principal',
            field=models.CharField(choices=[('Ropa', 'Ropa'), ('Hogar-Deco', 'Hogar Deco'), ('Accesorios', 'Accesorios'), ('Recetas', 'Recetas'), ('Tecnologia', 'Tecnologia'), ('Libros', 'Libros'), ('Plantas', 'Plantas'), ('Fotografia', 'Fotografia'), ('Academico', 'Academico')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='pagehub',
            name='sub_categoria',
        ),
        migrations.AddField(
            model_name='pagehub',
            name='sub_categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
