# Generated by Django 5.1.7 on 2025-05-15 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagehub', '0004_pagehub_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='Vacio', max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría Principal',
                'verbose_name_plural': 'Categorías Principales',
            },
        ),
        migrations.AlterField(
            model_name='pagehub',
            name='categoria_principal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagehub.categoriaprincipal'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria_principal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagehub.categoriaprincipal'),
        ),
    ]
