# Generated by Django 5.1.7 on 2025-05-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagehub', '0005_categoriaprincipal_alter_pagehub_categoria_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaprincipal',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
