# Generated by Django 5.1.7 on 2025-05-15 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagehub', '0006_alter_categoriaprincipal_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehub',
            name='sub_categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagehub.subcategoria'),
        ),
    ]
