# Generated by Django 5.1.7 on 2025-05-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagehub', '0009_categoriaprincipal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaprincipal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
