# Generated by Django 5.1.7 on 2025-03-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageHub',
        ),
        migrations.DeleteModel(
            name='SubCategoria',
        ),
    ]
